name: Humo py{lint|right}

on:
  push:
    branches:
      - '*'
  pull_request:
    branches: [ "main" , "dev"]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8"]
        os: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest pylint pyright
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Analysing the code with pylint
      run: |
        git submodule init
        git submodule update
        pylint $(git ls-files '*.py') --rcfile=.pylintrc
    - name: Analysing the code with pyright
      run: |
        pyright $(git ls-files '*.py') --lib
